webapp/calculate/forms.py
"""
    Apache License 2.0 Copyright (c) 2022 Pavel Bystrov
    Recommendation forms
"""
from flask_wtf import FlaskForm
from wtforms import SubmitField


class CalcForm(FlaskForm):
    """ Calc Form """
    ok = SubmitField("OK", render_kw={"class": "btn btn-primary"})

webapp/calculate/views.py
"""
    Apache License 2.0 Copyright (c) 2022 Pavel Bystrov
    blueprint for recommendations
"""
from flask import render_template, Blueprint, redirect, \
    url_for, flash
from flask_login import login_required
from webapp.business_logic import save_users_ratings
from webapp.utils.recipes_util import calculate_embeddings
from webapp.config import CALC_MODEL
from webapp.calculate.forms import CalcForm

blueprint = Blueprint("calculate", __name__, url_prefix="/calculate")


@blueprint.route("/calculate")
@login_required
def calculate():
    """ show calculate form """
    form = CalcForm()
    return render_template("calculate/calculate.html",
                           title=CALC_MODEL,
                           form=form)


@blueprint.route("/process_calculate", methods=["POST"])
@login_required
def process_calculate():
    """ calculate embeddings for CF-model"""
    form = CalcForm()
    if form.validate_on_submit():
        save_users_ratings(file_name="data/users_ratings.csv")
        calculate_embeddings()
        flash("модель повторно рассчитана")
        return redirect(url_for("index"))
    flash("Ошибка в calculate form")
    return redirect(url_for("calculate.calculate"))

webapp/templates/calculate/calculate.html
{% extends "bootstrap.html" %}
{% block content %}
    <div class="container">
        <div class="row">
		    <div class="col-4">
            </div>
			<div class="col-4">
			{% with messages = get_flashed_messages() %}
				{% if messages %}
				<div class="alert alert-warning" role="alert">
					{% for message in messages %}
						{{ message }}<br>
					{% endfor %}
				</div>
				{% endif %}
			{% endwith %}
			<form action="{{ url_for('calculate.process_calculate')}}" method="POST">
				{{ form.hidden_tag() }}
                <center><b>ПЕРЕРАСЧЕТ МОДЕЛИ</b></center>
                <br>
				<center>Расчет модели может выполняться до 5 минут</center>
                <br>
				<center>{{ form.ok }}</center>
			</form>
			</div>
            <div class="col-4">
            </div>
        </div>
    </div>
{% endblock %}