webapp/stat/models.py
"""
    Apache License 2.0 Copyright (c) 2022 Pavel Bystrov
   model for python internal SQLite db
"""
from webapp.db import DB


class Recipe(DB.Model):
    """ Recipe table """
    __tablename__ = "recipe"
    id = DB.Column(DB.Integer, primary_key=True)
    author_id = DB.Column(DB.Integer)
    dish_type = DB.Column(DB.String(100))
    cusine_type = DB.Column(DB.String(100))
    name = DB.Column(DB.String(300))
    cooking = DB.Column(DB.String(2000))
    minutes = DB.Column(DB.Integer)
    old_id = DB.Column(DB.Integer)

    def __repr__(self):
        """repr method"""
        return f"<Recipe {self.id} {self.name}>"


class Ingredient(DB.Model):
    __tablename__ = "ingredient"
    id = DB.Column(DB.Integer, primary_key=True)
    name = DB.Column(DB.String(160), index=True, unique=False)

    def __repr__(self):
        """repr method"""
        return f"<Ingredient {self.id} {self.name}>"


class Measure(DB.Model):
    """ table with Measures """
    __tablename__ = "measure"
    id = DB.Column(DB.Integer, primary_key=True)
    name = DB.Column(DB.String(160), index=True, unique=False)

    def __repr__(self):
        """repr method"""
        return f"<Measure {self.id} {self.name}>"


class IngredientGroup(DB.Model):
    """IngredientGroup table"""
    __tablename__ = "ingredient_group"
    id = DB.Column(DB.Integer, primary_key=True)
    ingredient_id = DB.Column(DB.Integer, DB.ForeignKey("ingredient.id"))
    ingredients = DB.relationship("Ingredient",
                                  backref=DB.backref("ingredient_group"))
    measure_id = DB.Column(DB.Integer, DB.ForeignKey("measure.id"))
    measures = DB.relationship("Measure",
                               backref=DB.backref("ingredient_group"))

    def __repr__(self):
        """repr method"""
        return f"<IngredientGroup recipe{self.recipe_id} {self.ingredient_id}>"


class Author(DB.Model):
    """Ingredient model"""
    __tablename__ = "author"
    id = DB.Column(DB.Integer, primary_key=True)
    name = DB.Column(DB.String(128), index=True, unique=False)

    def __repr__(self):
        """repr method"""
        return f"<Author {self.id} {self.name}>"


class Interactions(DB.Model):
    """Interactions model for collaborative filtering"""
    __tablename__ = "interactions"
    author_id = DB.Column(DB.Integer, primary_key=True)
    recipe_id = DB.Column(DB.Integer, primary_key=True)
    created = DB.Column(DB.Date)
    rating = DB.Column(DB.Float)

    def __repr__(self):
        """repr method"""
        return f"<Interaction {self.author_id} {self.recipe_id}>"


class Recipes(DB.Model):
    """ Recipes table """
    __tablename__ = "recipes"
    id = DB.Column(DB.Integer, primary_key=True)
    creator_id = DB.Column(DB.Integer)
    dish_type = DB.Column(DB.String(64))
    cusine_type = DB.Column(DB.String(64))
    name = DB.Column(DB.String(300))
    cooking_directions = DB.Column(DB.String(2000))
    pic_url = DB.Column(DB.String(300))
    pic = DB.Column(DB.String(100))
    ingredient_group_id = DB.Column(DB.Integer,
                                    DB.ForeignKey("ingredient_group.id"))
    ingredient_group = DB.relationship('IngredientGroup',
                                       backref=DB.backref('recipes',
                                                          uselist=False))

    def __repr__(self):
        """repr method"""
        return f"<Recipes object {self.id} {self.name}>"


class Note(DB.Model):
    """ Note table """
    __tablename__ = "note"
    id = DB.Column(DB.Integer, primary_key=True)
    name = DB.Column(DB.String(300))
    pic_url = DB.Column(DB.String(300))
    pic = DB.Column(DB.String(100))
    ingredients = DB.Column(DB.String(2000))
    mera = DB.Column(DB.String(2000))
    directions = DB.Column(DB.String(2000))
    cusine = DB.Column(DB.String(100))
    typed = DB.Column(DB.String(100))
    url = DB.Column(DB.String(300))

    def __repr__(self):
        """repr method"""
        return f"<temp note {self.id} {self.name}>"

webapp/stat/forms.py
""" Recommend form """
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired
from wtforms import Form, FieldList, FormField, IntegerField, \
    StringField, SubmitField
from wtforms import validators


class LapForm(Form):
    """ Subform """
    ingredient = StringField('ингредиент',
                             validators=[DataRequired(),
                                         validators.Length(max=150)],
                             render_kw={"class": "form-control"})
    how_much = StringField('сколько',
                           validators=[DataRequired(),
                                       validators.Length(max=150)],
                           render_kw={"class": "form-control"})


class RecipeForm(FlaskForm):
    """ class RecommendForm """
    dish = StringField("Название блюда",
                       validators=[DataRequired()],
                       render_kw={"class": "form-control"})
    directions = StringField("Рецепт",
                             validators=[DataRequired()],
                             render_kw={"class": "form-control"})
    rows = FieldList(FormField(LapForm), min_entries=1)
    submit = SubmitField("сохранить", render_kw={"class": "btn btn-primary"})


class NumberOfIngredientsForm(FlaskForm):
    """ class RecommendForm """
    number = IntegerField("Сколько ингредиентов в рецепте блюда",
                          validators=[DataRequired()],
                          render_kw={"class": "form-control"})
    submit = SubmitField("OK", render_kw={"class": "btn btn-primary"})

webapp/stat/views.py
"""
    Apache License 2.0 Copyright (c) 2022 Pavel Bystrov
    blueprint for statistics
"""
import logging
from flask import render_template, flash, redirect, url_for, Blueprint, request
from flask_wtf import FlaskForm
from wtforms import FormField, FieldList, StringField, SubmitField
from wtforms.validators import DataRequired
from webapp.business_logic import bulk_insert, \
    find_recipe_id_by_type_and_cuisine
from webapp.config import VALID_CUISINE, TYPE_MAP, FILL_RECIPE, INGREDIENTS_NUM
from webapp.dl import predict_types
from webapp.stat.forms import NumberOfIngredientsForm, LapForm
from webapp.stat.models import Note


blueprint = Blueprint("stat", __name__, url_prefix="/stat")


def create_template_form(num):
    """ create template form with min_entries = num"""

    class RecipeForm2(FlaskForm):
        """ class RecipeForm2 """
        dish = StringField("Название блюда",
                           validators=[DataRequired()],
                           render_kw={"class": "form-control"})
        directions = StringField("Рецепт",
                                 validators=[DataRequired()],
                                 render_kw={"class": "form-control"})
        rows = FieldList(FormField(LapForm), min_entries=num)
        submit = SubmitField("сохранить",
                             render_kw={"class": "btn btn-primary"})

    form = RecipeForm2()
    return form


def warning(message):
    """ warning function with flash message and logging"""
    logging.warning(message)
    flash(message)


def load_form_data(cur_form):
    """ load data using form and return data, type, and cuisine """
    ingredients = f"{[el['ingredient'] for el in cur_form.rows.data]}"
    mera = f"{[el['how_much'] for el in cur_form.rows.data]}"
    data = [{"name": cur_form.dish.data,
             "pic_url": "",
             "pic": "",
             "ingredients": ingredients,
             "mera": mera,
             "directions": f"{cur_form.directions.data}",
             "cusine": "",
             "typed": "",
             "url": "manual"}]
    cuisine, type_ = predict_types(data)
    data[0]["cusine"] = cuisine
    data[0]["typed"] = type_
    result = (data, type_, cuisine)
    return result


@blueprint.route("/fill_recipe/<int:num>", methods=["GET"])
def fill_recipe(num):
    """ simple cuisine recommendation """
    form = create_template_form(num)
    return render_template("stat/input_form.html",
                           num=num,
                           title=FILL_RECIPE,
                           form=form)


@blueprint.route("/fill_recipe/<int:num>", methods=["POST"])
def process_fill_recipe(num):
    """ simple cuisine recommendation """
    form = create_template_form(num)
    if form.validate_on_submit():
        data, type_, cuisine = load_form_data(form)
        bulk_insert(Note, data)
        flash(f"Рецепт сохранен - Тип {type_} кухня {cuisine}")
        return render_template("index.html")
    warning("Ошибка валидации рецепта блюда")
    return redirect(f"/stat/fill_recipe/{num}")


@blueprint.route("/search_cuisine", methods=["GET"])
def search_cuisine():
    """ simple cuisine recommendation """
    title = "Dish Recommendation"
    return render_template("stat/search_cuisine.html", title=title)


@blueprint.route("/search_cuisine", methods=["POST"])
def process_search_cuisine():
    """ process simple cuisine recommendation """
    dish = request.form.get("dish")
    cuisine = request.form.get("cuisine")
    if dish in TYPE_MAP.keys() and cuisine in VALID_CUISINE:
        dish_id = find_recipe_id_by_type_and_cuisine(dish, cuisine)
        return redirect(f"/recommend/recipe/{dish_id}")
    wrn = f"Ошибка валидации поисковой формы с типом:{dish} и кухней:{cuisine}"
    warning(wrn)
    return redirect(url_for("stat.search_cuisine"))


@blueprint.route("/new_recipe", methods=["GET"])
def new_recipe():
    """ create new recipe """
    form = NumberOfIngredientsForm()
    return render_template("stat/input_number.html",
                           title=INGREDIENTS_NUM,
                           form=form)


@blueprint.route("/new_recipe", methods=["POST"])
def process_new_recipe():
    """ process new recipe """
    form = NumberOfIngredientsForm()
    if form.validate_on_submit():
        num = form.number.data
        return redirect(f"/stat/fill_recipe/{num}")
    warning("Ошибка валидации формы с количеством ингредиентов")
    return redirect(url_for("stat.new_recipe"))

webapp/templates/stat/input_form.html
{% extends "bootstrap.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-2">
        </div>
        <div class="col-8">
			{% with messages = get_flashed_messages() %}
				{% if messages %}
				<div class="alert alert-warning" role="alert">
					{% for message in messages %}
						{{ message }} <br>
					{% endfor %}
				</div>
				{% endif %}
			{% endwith %}
            <form action="/stat/fill_recipe/{{ num }}" method="POST">
				{{ form.hidden_tag() }}
				<div class="form-group">
					{{ form.dish.label }}<br>
					{{ form.dish() }}<br>
				</div>
				<div class="form-floating">
				  <!--textarea class="form-control" id="floatingTextarea2" style="height: 100px"> placeholder=""
				  </textarea>
				  <label for="floatingTextarea2">{{ form.directions.label }}
				  </label-->
					{{ form.directions.label }} <br>
					{{ form.directions() }} <br>
				</div>
				{% for my_form in form.rows %}
					<div class="input-group">
					  <span class="input-group-text"> ингредиент и количество </span>
						{% for field in my_form %}
							{{ field() }}
						{% endfor %}
					</div>
				{% endfor %}
                <center>
				{{ form.submit }}
                </center>
            </form>
        </div>
        <div class="col-2">
        </div>
    </div>
</div>
{% endblock %}

webapp/templates/stat/input_number.html
{% extends "bootstrap.html" %}
{% block content %}
    <div class="container">
        <div class="row">
		    <div class="col-4">
            </div>
			<div class="col-4">
			{% with messages = get_flashed_messages() %}
				{% if messages %}
				<div class="alert alert-warning" role="alert">
					{% for message in messages %}
						{{ message }}<br>
					{% endfor %}
				</div>
				{% endif %}
			{% endwith %}
			<form action="{{ url_for('stat.new_recipe')}}" method="POST">
				{{ form.hidden_tag() }}
				<div class="form-group">
					{{ form.number.label }}
                    <br>
					{{ form.number() }}
				</div>
                <center>
				{{ form.submit }}
                </center>
			</form>
			</div>
		    <div class="col-4">
            </div>
        </div>
    </div>
{% endblock %}

webapp/templates/stat/recipe.html
{% extends "bootstrap.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-4">
        </div>
        <div class="col-8">
			<b>рецепт блюда<b>
			<br>
			{% for message in answers %}
				<b>{{ message }}<b>
				<br>
                <br>
			{% endfor %}
        </div>
    </div>
</div>
{% endblock %}

webapp/templates/stat/recipes.html
{% extends "bootstrap_album.html" %}
{% block content %}
	<br>
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text"> {{ message1 }} <br></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text"> {{ message2 }} <br></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>

       <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text"> {{ message3 }} <br></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

webapp/templates/stat/recipes2.html
{% extends "bootstrap_album.html" %}
{% block content %}
	<br>
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text"> {{ message1 }} <br></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text"> {{ message2 }} <br></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>

       <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text"> {{ message3 }} <br></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

webapp/templates/stat/recommendation.html
{% extends "bootstrap.html" %}
{% block content %}
    <div class="container">
        <div class="row">
		    <div class="col-4">
            </div>
			<div class="col-4">
			{% with messages = get_flashed_messages() %}
				{% if messages %}
				<div class="alert alert-warning" role="alert">
					{% for message in messages %}
						{{ message }}<br>
					{% endfor %}
				</div>
				{% endif %}
			{% endwith %}
			<form action="{{ url_for('stat.search_cuisine')}}" method="POST">
				{{ form.hidden_tag() }}
				<div class="form-group">
					{{ form.search.label }}<br>
					{{ form.search() }}
				</div>
				<div class="form-group">
					{{ form.cuisine.label }}<br>
					{{ form.cuisine() }}
				</div>
                <center>
				{{ form.submit }}
                </center>
			</form>
			</div>
            <div class="col-4">
            </div>
        </div>
    </div>
{% endblock %}

webapp/templates/stat/search_cuisine.html
{% extends "bootstrap.html" %}
{% block content %}
    <div class="container">
        <div class="row">
		    <div class="col-4">
            </div>
			<div class="col-4">
			{% with messages = get_flashed_messages() %}
				{% if messages %}
				<div class="alert alert-warning" role="alert">
					{% for message in messages %}
						{{ message }}<br>
					{% endfor %}
				</div>
				{% endif %}
			{% endwith %}
			<form action="{{ url_for('stat.process_search_cuisine')}}" method="POST">
				{{ form.hidden_tag() }}
				<div class="form-group">
					{{ form.search.label }}<br>
					{{ form.search() }}
				</div>
				<div class="form-group">
					{{ form.cuisine.label }}<br>
					{{ form.cuisine() }}
				</div>
				{{ form.submit }}
			</form>
			</div>
            <div class="col-4">
            </div>
        </div>
    </div>
{% endblock %}