webapp/calculate/forms.py
"""
    Apache License 2.0 Copyright (c) 2022 Pavel Bystrov
    Recommendation forms
"""
from flask_wtf import FlaskForm
from wtforms import SubmitField


class CalcForm(FlaskForm):
    """ Calc Form """
    ok = SubmitField("OK", render_kw={"class": "btn btn-primary"})

webapp/calculate/views.py
"""
    Apache License 2.0 Copyright (c) 2022 Pavel Bystrov
    blueprint for recommendations
"""
from flask import render_template, Blueprint, redirect, \
    url_for, flash
from flask_login import login_required
from webapp.business_logic import save_users_ratings
from webapp.utils.recipes_util import calculate_embeddings
from webapp.config import CALC_MODEL
from webapp.calculate.forms import CalcForm

blueprint = Blueprint("calculate", __name__, url_prefix="/calculate")


@blueprint.route("/calculate")
@login_required
def calculate():
    """ show calculate form """
    form = CalcForm()
    return render_template("calculate/calculate.html",
                           title=CALC_MODEL,
                           form=form)


@blueprint.route("/process_calculate", methods=["POST"])
@login_required
def process_calculate():
    """ calculate embeddings for CF-model"""
    form = CalcForm()
    if form.validate_on_submit():
        save_users_ratings(file_name="data/users_ratings.csv")
        calculate_embeddings()
        flash("модель повторно рассчитана")
        return redirect(url_for("index"))
    flash("Ошибка в calculate form")
    return redirect(url_for("calculate.calculate"))

webapp/recommend/views.py
"""
    Apache License 2.0 Copyright (c) 2022 Pavel Bystrov
    blueprint for recommendations
"""
from flask import render_template, Blueprint, request, redirect, \
    url_for, flash
from flask_login import login_required, current_user
import logging
from webapp.business_logic import find_recipe, \
    insert_or_update_rating
from webapp.utils.recipes_util import find_enough_recommended_recipes, \
    to_list
from webapp.config import RECOMMEND_ACTIONS, COLORS, RECOMMEND_ACT, \
    RATE_ACT, RATE_ACTIONS, VALID_CUISINE, TYPE_MAP, RECIPE, \
    RECOMMEND_RECIPES, USER_BASED, ITEM_BASED, \
    USER_BASED_RECOMMENDATION, ITEM_BASED_RECOMMENDATION

blueprint = Blueprint("recommend", __name__, url_prefix="/recommend")


def fill_params(type_):
    """ fill mandatory params """
    if type_ in TYPE_MAP.keys():
        dish_type = type_
        text = f"Рецепты с типом {type_}".upper()
        cuisine = None
    else:
        dish_type = None
        text = f"{type_} кухня".upper()
        cuisine = type_
    return dish_type, cuisine, text


def find_index_of_form(form, actions, action):
    """ find index of form function """
    try:
        index = actions.index(form.get(action))
        return index
    except ValueError:
        err = f"Value Error in find_index_of_form: {form} {actions} {action}"
        logging.error(err)


def log_and_flash(msg):
    """ logging """
    logging.warning(f"Введен некорректный {msg}")
    flash(f"Введите корректный {msg}")


@blueprint.route("/recommend")
@login_required
def recommend():
    """ recipe recommendation by cuisine """
    return render_template("recommend/select_cuisine.html",
                           title="Выбор кухни")


@blueprint.route("/recommend", methods=["POST"])
@login_required
def process_recommend():
    """ process recipe recommendation by cuisine """
    type_ = request.form.get("cuisine")
    if type_ in VALID_CUISINE:
        return redirect(f"/recommend/recipes/{type_}/{USER_BASED}")
    log_and_flash(f"тип кухни: {type_}")
    return render_template("recommend/select_cuisine.html",
                           title="Выбор кухни")


@blueprint.route("/recommend_by_type")
@login_required
def recommend_by_type():
    """ recipe recommendation by type """
    return render_template("recommend/recommend_by_type_user_based.html",
                           title=USER_BASED_RECOMMENDATION)


@blueprint.route("/recommend_by_type", methods=["POST"])
@login_required
def process_recommend_by_type():
    """ process recipe recommendation by type """
    type_ = request.form.get("dish")
    if type_ in TYPE_MAP.keys():
        return redirect(f"/recommend/recipes/{type_}/{USER_BASED}")
    log_and_flash(f"тип: {type_} (user based filtration)")
    return render_template("recommend/recommend_by_type_user_based.html",
                           title=USER_BASED_RECOMMENDATION)


@blueprint.route("/recipes/<string:type_>/<string:filtering>")
@login_required
def recipes(type_, filtering):
    """ recipe recommendation """
    user = current_user
    dish_type, cuisine, text = fill_params(type_)
    messages, ids = find_enough_recommended_recipes(user.id,
                                                    cuisine,
                                                    dish_type)
    messages = messages[:9]
    return render_template("recommend/recipes.html",
                           title=RECOMMEND_RECIPES,
                           text=text,
                           messages=messages,
                           type_=type_,
                           filtering=filtering)


@blueprint.route("/recipes/<string:type_>/<string:filtering>",
                 methods=["POST"])
@login_required
def process_recipes(type_, filtering):
    """ process recipe recommendation """
    user = current_user
    dish_type, cuisine, text = fill_params(type_)
    if filtering == USER_BASED or filtering == ITEM_BASED:
        messages, ids = find_enough_recommended_recipes(user.id,
                                                        cuisine,
                                                        dish_type)
    else:
        flash(f"Неправильный тип фильтрации {filtering}")
        return redirect(url_for("index"))
    ids = ids[:9]
    index = find_index_of_form(request.form,
                               RECOMMEND_ACTIONS, RECOMMEND_ACT)
    if index is not None and len(ids) > index:
        if ids[index] >= 0:
            logging.info(f"user:{user.id} /recommend/recipe/{ids[index]}")
            return redirect(f"/recommend/recipe/{ids[index]}")
    flash("Ошибка валидации")
    return redirect(url_for("index"))


@blueprint.route('/recipe/<int:num>', methods=["GET"])
@login_required
def recipe(num):
    """ show simple recipe with ingedients table """
    rec = find_recipe(num)
    if rec:
        arr = [rec.name,
               rec.typed] + [" ".join(to_list(rec.directions))]
        ingr = to_list(rec.ingredients)
        zipped = zip([COLORS[i % 5] for i in range(len(ingr))],
                     ingr,
                     to_list(rec.mera))
        return render_template("recommend/show_recipe.html",
                               main_text=RECIPE,
                               num=num,
                               messages=arr,
                               items=zipped)
    logging.error(f"Ошибка: рецепт {num} не найден")
    flash(f"Ошибка: рецепт {num} не найден")
    return redirect(url_for("index"))


@blueprint.route('/recipe/<int:num>', methods=["POST"])
@login_required
def process_recipe(num):
    """ show simple recipe with ingedients table """
    rec = find_recipe(num)
    if rec:
        index = find_index_of_form(request.form,
                                   RATE_ACTIONS,
                                   RATE_ACT)
        if index is not None:
            index += 1
            user = current_user
            insert_or_update_rating(int(index), user.username, int(num))
            flash("Данные сохранены")
            logging.info(f"user:{user.id} /recommend/recipe/{num}")
            return redirect(f"/recommend/recipe/{num}")
        else:
            msg = "Ошибка поиска рецепта"
    else:
        msg = "Ошибка валидации рецепта"
    flash(msg)
    return redirect(url_for("index"))


@blueprint.route("/recommend_by_type_item_based")
@login_required
def recommend_by_type_item_based():
    """ recipe recommendation by type """
    return render_template("recommend/recommend_by_type_item_based.html",
                           title=ITEM_BASED_RECOMMENDATION)


@blueprint.route("/recommend_by_type_item_based", methods=["POST"])
@login_required
def process_recommend_by_type_item_based():
    """ process recipe recommendation by type """
    type_ = request.form.get("dish")
    if type_ in TYPE_MAP.keys():
        return redirect(f"/recommend/recipes/{type_}/{ITEM_BASED}")
    log_and_flash(f"тип: {type_} (item based filtration)")
    return render_template("recommend/recommend_by_type_item_based.html",
                           title=ITEM_BASED_RECOMMENDATION)

webapp/templates/recommend/calculate.html
{% extends "bootstrap.html" %}
{% block content %}
    <div class="container">
        <div class="row">
		    <div class="col-4">
            </div>
			<div class="col-4">
			{% with messages = get_flashed_messages() %}
				{% if messages %}
				<div class="alert alert-warning" role="alert">
					{% for message in messages %}
						{{ message }}<br>
					{% endfor %}
				</div>
				{% endif %}
			{% endwith %}
			<form action="{{ url_for('recommend.process_calculate')}}" method="POST">
				{{ form.hidden_tag() }}
                <center><b>ПЕРЕРАСЧЕТ МОДЕЛИ</b></center>
                <br>
				<center>Расчет модели может выполняться до 5 минут</center>
                <br>
				<center>{{ form.ok }}</center>
			</form>
			</div>
            <div class="col-4">
            </div>
        </div>
    </div>
{% endblock %}

webapp/templates/recommend/recipes.html
{% extends "bootstrap.html" %}
{% block content %}
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">{{ text }}</h1>
      </div>
    </div>
  </section>
  <br>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text"> {{ messages[0] }} <br></p>
              <div class="d-flex justify-content-between align-items-center">
			    <form action="/recommend/recipes/{{ type_ }}/{{ filtering }}" method="POST">
                    <input type="submit" value="Рецепт 1" name="action_" class="btn btn-primary" />
			    </form>
                <small class="text-muted"> </small>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text"> {{ messages[1] }} <br></p>
              <div class="d-flex justify-content-between align-items-center">
			    <form action="/recommend/recipes/{{ type_ }}/{{ filtering }}" method="POST">
                    <input type="submit" value="Рецепт 2" name="action_" class="btn btn-primary" />
			    </form>
                <small class="text-muted"> </small>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text"> {{ messages[2] }} <br></p>
              <div class="d-flex justify-content-between align-items-center">
			    <form action="/recommend/recipes/{{ type_ }}/{{ filtering }}" method="POST">
                    <input type="submit" value="Рецепт 3" name="action_" class="btn btn-primary" />
			    </form>
                <small class="text-muted"> </small>
              </div>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text"> {{ messages[3] }} <br></p>
              <div class="d-flex justify-content-between align-items-center">
			    <form action="/recommend/recipes/{{ type_ }}/{{ filtering }}" method="POST">
                    <input type="submit" value="Рецепт 4" name="action_" class="btn btn-primary" />
			    </form>
                <small class="text-muted"> </small>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text"> {{ messages[4] }} <br></p>
              <div class="d-flex justify-content-between align-items-center">
			    <form action="/recommend/recipes/{{ type_ }}/{{ filtering }}" method="POST">
                    <input type="submit" value="Рецепт 5" name="action_" class="btn btn-primary" />
			    </form>
                <small class="text-muted"> </small>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text"> {{ messages[5] }} <br></p>
              <div class="d-flex justify-content-between align-items-center">
			    <form action="/recommend/recipes/{{ type_ }}/{{ filtering }}" method="POST">
                    <input type="submit" value="Рецепт 6" name="action_" class="btn btn-primary" />
			    </form>
                <small class="text-muted"> </small>
              </div>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text"> {{ messages[6] }} <br></p>
              <div class="d-flex justify-content-between align-items-center">
			    <form action="/recommend/recipes/{{ type_ }}/{{ filtering }}" method="POST">
                    <input type="submit" value="Рецепт 7" name="action_" class="btn btn-primary" />
			    </form>
                <small class="text-muted"> </small>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text"> {{ messages[7] }} <br></p>
              <div class="d-flex justify-content-between align-items-center">
			    <form action="/recommend/recipes/{{ type_ }}/{{ filtering }}" method="POST">
                    <input type="submit" value="Рецепт 8" name="action_" class="btn btn-primary" />
			    </form>
                <small class="text-muted"> </small>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text"> {{ messages[8] }} <br></p>
              <div class="d-flex justify-content-between align-items-center">
			    <form action="/recommend/recipes/{{ type_ }}/{{ filtering }}" method="POST">
                    <input type="submit" value="Рецепт 9" name="action_" class="btn btn-primary" />
			    </form>
                <small class="text-muted"> </small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

webapp/templates/recommend/recommend_by_type_item_based.html
{% extends "bootstrap.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-4">
        </div>
        <div class="col-4">
			{% with messages = get_flashed_messages() %}
				{% if messages %}
				<div class="alert alert-warning" role="alert">
					{% for message in messages %}
						{{ message }}<br>
					{% endfor %}
				</div>
				{% endif %}
			{% endwith %}
            <form action="{{ url_for('recommend.process_recommend_by_type_item_based')}}" method="POST">
                {{ title }}<br>
                <select class="form-select form-select-lg mb-3" aria-label="select-lg example" name="dish">
                  <option selected>вторые блюда</option>
                  <option value="десерты">десерты</option>
                  <option value="завтраки">завтраки</option>
                  <option value="закуски">закуски</option>
                  <option value="салаты">салаты</option>
                  <option value="соусы">соусы</option>
                  <option value="супы и первые блюда">супы и первые блюда</option>
                </select>
                <center>
                <input type="submit" value="OK" name="action_" class="btn btn-primary" />
                </center>
            </form>
        </div>
        <div class="col-4">
        </div>
    </div>
</div>
{% endblock %}

webapp/templates/recommend/recommend_by_type_user_based.html
{% extends "bootstrap.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-4">
        </div>
        <div class="col-4">
			{% with messages = get_flashed_messages() %}
				{% if messages %}
				<div class="alert alert-warning" role="alert">
					{% for message in messages %}
						{{ message }}<br>
					{% endfor %}
				</div>
				{% endif %}
			{% endwith %}
            <form action="{{ url_for('recommend.process_recommend_by_type')}}" method="POST">
                {{ title }}<br>
                <select class="form-select form-select-lg mb-3" aria-label="select-lg example" name="dish">
                  <option selected>вторые блюда</option>
                  <option value="десерты">десерты</option>
                  <option value="завтраки">завтраки</option>
                  <option value="закуски">закуски</option>
                  <option value="салаты">салаты</option>
                  <option value="соусы">соусы</option>
                  <option value="супы и первые блюда">супы и первые блюда</option>
                </select>
                <center>
                <input type="submit" value="OK" name="action_" class="btn btn-primary" />
                </center>
            </form>
        </div>
        <div class="col-4">
        </div>
    </div>
</div>
{% endblock %}

webapp/templates/recommend/select_cuisine.html
{% extends "bootstrap.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-4">
        </div>
        <div class="col-4">
			{% with messages = get_flashed_messages() %}
				{% if messages %}
				<div class="alert alert-warning" role="alert">
					{% for message in messages %}
						{{ message }}<br>
					{% endfor %}
				</div>
				{% endif %}
			{% endwith %}
            <form action="{{ url_for('recommend.process_recommend')}}" method="POST">
                {{ title }}<br>
                <select class="form-select form-select-lg mb-3" aria-label="select-lg example" name="cuisine">
                  <option selected>русская</option>
                  <option value="азиатская">азиатская</option>
                  <option value="европейская">европейская</option>
                  <option value="мексиканская">мексиканская</option>
                  <option value="африканская">африканская</option>
                </select>
                <center>
                <input type="submit" value="OK" name="action_" class="btn btn-primary" />
                </center>
            </form>
        </div>
        <div class="col-4">
        </div>
    </div>
</div>
{% endblock %}

webapp/templates/recommend/select_type.html
{% extends "bootstrap.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-4">
        </div>
        <div class="col-4">
			{% with messages = get_flashed_messages() %}
				{% if messages %}
				<div class="alert alert-warning" role="alert">
					{% for message in messages %}
						{{ message }}<br>
					{% endfor %}
				</div>
				{% endif %}
			{% endwith %}
            <form action="{{ url_for('recommend.process_recommend_by_type')}}" method="POST">
                {{ title }}<br>
                <select class="form-select form-select-lg mb-3" aria-label="select-lg example" name="dish">
                  <option selected>вторые блюда</option>
                  <option value="десерты">десерты</option>
                  <option value="завтраки">завтраки</option>
                  <option value="закуски">закуски</option>
                  <option value="салаты">салаты</option>
                  <option value="соусы">соусы</option>
                  <option value="супы и первые блюда">супы и первые блюда</option>
                </select>
                <center>
                <input type="submit" value="OK" name="action_" class="btn btn-primary" />
                </center>
            </form>
        </div>
        <div class="col-4">
        </div>
    </div>
</div>
{% endblock %}

webapp/templates/recommend/show_recipe.html
{% extends "bootstrap.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-2">
        </div>
        <div class="col-8">
            {% with msgs = get_flashed_messages() %}
				{% if msgs %}
				<div class="alert alert-warning" role="alert">
					{% for msg in msgs %}
						{{ msg }}<br>
					{% endfor %}
				</div>
				{% endif %}
			{% endwith %}
			{% for message in messages %}
                <center>{{ message }}</center>
                <br>
			{% endfor %}
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Ингредиенты</th>
                  <th scope="col">Количество</th>
                </tr>
              </thead>
              <tbody>
			    {% for elem in items %}
                <tr class="{{ elem[0] }}">
                  <th scope="row"> </th>
                  <td>{{ elem[1] }}</td>
                  <td>{{ elem[2] }}</td>
                </tr>
			    {% endfor %}
              </tbody>
            </table>
            <form action="/recommend/recipe/{{ num }}" method="POST">
                <div class="form-group">
					Оцените рецепт:<br>
				</div>
                <input type="submit" value="1" name="action" class="btn btn-primary" />
                <input type="submit" value="2" name="action" class="btn btn-primary" />
                <input type="submit" value="3" name="action" class="btn btn-primary" />
                <input type="submit" value="4" name="action" class="btn btn-primary" />
                <input type="submit" value="5" name="action" class="btn btn-primary" />
            </form>
              <br>
        </div>
        <div class="col-2">
        </div>
    </div>
</div>

{% endblock %}